### ISSUE TITLE
RFE: enable encryption at rest where possible 

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#17]
All components of the stack (S3 SSE, Redis, RDS, ...) should use at least encryption at rest since users might be storing sensitive data depending on their legal requirements.

**Comment by mariusmitrofan** [comment]
Encryption level status:
- S3 => not added, can be done easily through CloudFormation
- RDS => already done. check https://github.com/Rungutan/sentry-performance-monitoring/blob/main/cloudformation-template.yaml#L1402-L1403
- Redis => cannot be done as it is not supported by CloudFormation -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html
- Kafka => already done. check https://github.com/Rungutan/sentry-performance-monitoring/blob/main/cloudformation-template.yaml#L1318-L1324
- ClickHouse -> volumes themselves can be encrypted by updating the `VolumeConfiguration` of the Layer property as defined here -> https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-opsworks-layer-volumeconfiguration.html#cfn-opsworks-layer-volumeconfiguration-encrypted

**Comment by nodomain** [comment]
This seems to be another +1 for the ElastiCache Replication Group (see #16): https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticache-replicationgroup.html#cfn-elasticache-replicationgroup-atrestencryptionenabled

Let's add S3 and ClickHouse encryption. I'll see if I can get this running and file a PR.
