### ISSUE TITLE
The EMAIL_USE_SSL setting is deprecated. Please use SENTRY_OPTIONS['mail.use-ssl'] instead.

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#2]
This came to my attention when looking at the Warnings in the admin menu. 

The EMAIL_USE_SSL setting is deprecated. Please use SENTRY_OPTIONS['mail.use-ssl'] instead.

**Comment by nodomain** [comment]
Seems to be similar to https://github.com/getsentry/onpremise/issues/718
![image](https://user-images.githubusercontent.com/104389/105246149-24b2db00-5b73-11eb-9095-c01e708b4a72.png)

**Comment by mariusmitrofan** [comment]
The warning in the top bar no longer appears, but you'll still see it in the logs due to a bug in Sentry unfortunately

**Comment by nodomain** [comment]
Awesome.

Any idea how to mitigate this?

```
ClickHouseBoostrapLambdaResultSingleExecution | UPDATE_FAILED | Failed to update resource. See the details in CloudWatch Log Stream: 2021/01/21/[$LATEST]9cbac80fd00446909ac0fb22631c02f4 | Custom::ClickHouseBootstrapSingleExecution | 2021/01/21/[$LATEST]9cbac80fd00446909ac0fb22631c02f4
```


Afterwards it rolls back.
I uploaded the new CloudFormation file and updated the parameters accordingly (1.2.1 instead of latest).

**Comment by nodomain** [comment]
Note: I am unable to find the referenced logstream.

**Comment by mariusmitrofan** [comment]
I remember already testing update from 1.0.0 and 1.1.0 to latest and didn't have any problems.

To find the log stream you have to search the log group by the stack name and then it should be there.

Aka if my stack would be "sentry-rungutan-test" then this link would show me directly those correct log groups -> 

https://console.aws.amazon.com/cloudwatch/home#logsV2:log-groups$3FlogGroupNameFilter$3Dsentry-rungutan-test

PS: Make sure you're in the proper region

**Comment by mariusmitrofan** [comment]
btw @nodomain  -> if you don't have any data in it, just delete the stack and create a new one :)

**Comment by nodomain** [comment]
Found it. Mixed up the time zones.

```json
{
    "Status": "FAILED",
    "Reason": "See the details in CloudWatch Log Stream: 2021/01/21/[$LATEST]9cbac80fd00446909ac0fb22631c02f4",
    "PhysicalResourceId": "2021/01/21/[$LATEST]9cbac80fd00446909ac0fb22631c02f4",
    "StackId": "arn:aws:cloudformation:eu-central-1:722716701248:stack/Sentry/387ae980-5b2c-11eb-9af6-0a306114f79c",
    "RequestId": "4c27cbb5-a079-48d4-ac8c-832845186ddc",
    "LogicalResourceId": "ClickHouseBoostrapLambdaResultSingleExecution",
    "NoEcho": false,
    "Data": {
        "Reason": "string indices must be integers"
    }
}

```

**Comment by nodomain** [comment]
Unfortunately we are using it already :)

**Comment by mariusmitrofan** [comment]
> Unfortunately

So is it working now...?

**Comment by nodomain** [comment]
I’ll have a debugging session tonight and give you feedback. Trying to understand the various components at the moment.

**Comment by mariusmitrofan** [comment]
Let's do it together then.

Use calendly.com/marius-mitrofan to schedule a Zoom call!

**Comment by nodomain** [comment]
Thanks! Sent an invite.

**Comment by nodomain** [comment]
I think we can skip the Zoom call. I found it and proposed a fix.
Python noob here - feel free to improve it 🤓

**Comment by mariusmitrofan** [comment]
Thanks! Will include the changes a new PR which offers Slack integration as well.
