### ISSUE TITLE
Support for Graviton2 processors

### ISSUE THREAD

**Issue by eduardopuente** [Rungutan/sentry-fargate-cf-stack#22]
I would like to have support for the new Graviton2 processors, which include the following instance classes:
t4g, c6g, m6g, r6g. Many services like EC2 and RDS are already compatible.

**Comment by mariusmitrofan** [comment]
Notice:
- Although EC2 does support graviton instances, **OpsWorks does not**
- Although RDS (Native) PostgreSQL supports graviton instances, **Aurora PostgreSQL (which will be deployed as part of https://github.com/Rungutan/sentry-fargate-cf-stack/issues/16) does not**
- **Kafka MSK does not** support graviton instances
- ElastiCache **supports some graviton** instances
