### ISSUE TITLE
Update to 1.11.1 fails with Vendor response doesn't contain KafkaBroker1..3 key in object 

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#33]
On my staging environment everything went fine yesterday. On my production one it fails with these errors:
The only difference besides the instance type is that I manually extended the EBS storage on production already.

Please help - I already found that it seems to have something to do with the result of the lambda because it will output the keys only on "Create" but I am stuck. https://github.com/Rungutan/sentry-fargate-cf-stack/blob/main/cloudformation-template.yaml#L1828

```
CustomResource attribute error: Vendor response doesn't contain KafkaBroker3 key in object arn:aws:cloudformation:eu-central-1:722716701248:stack/sentry-prod/6e810c90-5cb1-11eb-8bbc-0207ca607726|KafkaGetBrokersLambdaResult|6c61345e-58f6-4b10-b64d-28e849cd4cdd in S3 bucket cloudformation-custom-resource-storage-eucentral1
```

<img width="1618" alt="image" src="https://user-images.githubusercontent.com/104389/106351948-c0fd8000-62df-11eb-8375-2d9765a17d8f.png">

Thanks

**Comment by nodomain** [comment]
I tried to further analyze the root cause of this by renaming the Kafka resource in the CF template to trigger the creation of a new Kafka cluster:

```yaml
ClusterName:
        Fn::Sub: ${AWS::StackName}-Kafka
```

Unfortunately this results in the same errors and the CF stack is rolled back.

The result indeed does not contain the requested keys.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/104389/106378567-392e7900-63a6-11eb-8811-e21ce13e7fcc.png">

**Comment by mariusmitrofan** [comment]
The https://github.com/Rungutan/sentry-fargate-cf-stack/releases/tag/1.11.2 release patch should fix this. I think it should work with your existing changed-outside-of-cloudformation Kafka cluster, but not 100% sure about it...

@nodomain

**Comment by nodomain** [comment]
Fixed it by temporarily renaming `KafkaGetBrokersLambdaResult` to `KafkaGetEndpointsLambdaResult` in the latest version and applying it. This seems to have triggered the needed changes that were prerequisite to a successful upgrade.
After the first run, I re-applied the original CF template in the latest version.
