### ISSUE TITLE
Support Geolocation using the default MaxMind integration

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#38]
Can you please extend the config to support geo location as described here?
https://develop.sentry.dev/self-hosted/geolocation/

This would be great!

**Comment by mariusmitrofan** [comment]
Acknowledged :)

Logic would be:

1) 
- add geoipupdate container as sidecar
- share path to mmdb file to sentry + relay

2)
- create EFS with KMS encrypted storage
- deploy one container of geoipupate and share path

Not sure which one is better right now (and cheaper)

**Comment by nodomain** [comment]
I vote for 1. 
The second approach sounds a too much.
