### ISSUE TITLE
Error events are accepted

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#43]
Hi,

I found https://github.com/getsentry/sentry/issues/22789 a while ago because I observed the same behavior with my Sentry instances. Would you mind checking if this can be set in your solution please?

Thanks.

**Comment by nodomain** [comment]
Can you please point me where to create the credentials that are needed for the "managed" mode?

**Comment by mariusmitrofan** [comment]
To be honest, I'm not completely sure how you can do that.

I remember looking into it a while back and AFAIR it comes down to this:
- generate credentials through shell command at sentry relay initialisation
- include those credentials in that relay config file
- test everything out and make sure its ok


This however I'm pretty sure requires you to fork this repo and maintain it at your own will, as I'm not entirely sure that the "managed" configuration can be maintained in a "generic" way...


If you do find any tutorial or "set of commands" that could help generalise this situation, I'm more than happy to assist in implementing them !

**Comment by nodomain** [comment]
Cool, looking into it with low priority.
