### ISSUE TITLE
Dropping ECR support broke my stack

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#44]
Hi,

please re-enable your registry, I am stuck in a loop - I realized something is wrong since "6 days" and tried to update to the new version. Unfortunately I had a typo in one of the image URLs and now I can't rollback due to:

STOPPED (CannotPullContainerError: inspect image has been retried 1 time(s): failed to resolve ref "public.ecr.aws/x7u7j5v7/sentry-relay:1.11.3": public.ecr.aws/x7u7j5v7/sentry-relay:1.11.3: not found)

Of course it worked fine on my stage stack but I messed my prod stack :-/
So it would be perfect if the ECR was back online again.

**Comment by mariusmitrofan** [comment]
@nodomain the ECR was recreated and contains tags 1.11.3 (your rollback problem tag).

Please use it to rollback and then switch to the docker community tag or "copy" the tags in your own ECR for reliability.

Please let me know when rollback is finished so I can drop it again.

PS: Issue #43 was created as part of tag 1.13.1 but its your own responsibility if you decide to move away from `proxy` relay mode, as the `managed` one comes with its own problems.

Cheers!

**Comment by nodomain** [comment]
Awesome. Fixed it!

Thank you so much.
