### ISSUE TITLE
Any plans to support newer Sentry releases?

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#47]
Hi,

I was wondering if and how to upgrade the stack to a more recent Sentry version.
The "on premise" repo already contains the 21.4.1 release.

https://github.com/getsentry/onpremise/releases/tag/21.4.1

Do you plan to upgrade?

Thx

**Comment by mariusmitrofan** [comment]
Merged in https://github.com/Rungutan/sentry-fargate-cf-stack/pull/48/files and released with tag 1.13.2
