### ISSUE TITLE
No events showing up in 1.13.2 (Sentry 21.4.1)

### ISSUE THREAD

**Issue by nodomain** [Rungutan/sentry-fargate-cf-stack#52]
After getting my DB migrations settled, I found that no new events are showing up in the issue list.

I suspect this change as the root cause: https://github.com/getsentry/onpremise/commit/4d7021729bbea1d1dda89696e41b4e05c995bce8#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

Furthermore I am not sure if this also needs to be changed:
https://github.com/getsentry/onpremise/commit/aecc75b1c91370469d501f51b139b7b4997c0995#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

And this:
https://github.com/getsentry/onpremise/commit/35a45ea7ae64b05ccf6a0c2f5bcbbaf204766c61#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

And this:
https://github.com/getsentry/onpremise/commit/e0dde9c57b9c04791935c5455c4ddcb6024e8c1f#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

Please have a look - I am stuck here 🍺

**Comment by nodomain** [comment]
Some more details: Performance measurements are still collected, emails are sent etc. 
Even mails about new events arrive but clicking on them bring up an error.

So it seems to partially work but some important piece is missing.

**Comment by mariusmitrofan** [comment]
@nodomain i'm on vacation with limited/no ability to actually work.

However, based on your last post, it seems as if you have DB problems, so might want to check the "sentry migrations" as well versus postgres.

Hope this helps. Cheers!

**Comment by nodomain** [comment]
Thanks for the hint, unfortunately: 

```bash
root@ip-172-80-72-96:/# sentry django migrate
10:17:57 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
10:17:57 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
10:18:02 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'slack.legacy-app'
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
```

And

```bash
root@ip-172-80-72-96:/# sentry upgrade
10:18:54 [WARNING] sentry.utils.geo: Error opening GeoIP database: /geoip/GeoLite2-City.mmdb
10:18:54 [WARNING] sentry.utils.geo: Error opening GeoIP database in Rust: /geoip/GeoLite2-City.mmdb
10:18:59 [INFO] sentry.plugins.github: apps-not-configured
* Unknown config option found: 'slack.legacy-app'
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  No migrations to apply.
Creating missing DSNs
Correcting Group.num_comments counter

```

**Comment by nodomain** [comment]
I was right. Events are back - I'll send a PR :)

**Comment by nodomain** [comment]
The root cause seems to have been a mix of missing services and this https://github.com/getsentry/snuba/issues/1527

**Comment by nodomain** [comment]
The most beautiful screenshot of the day :) "a few seconds ago"

![image](https://user-images.githubusercontent.com/104389/116829553-9e138e00-aba4-11eb-8ecb-7c1013cc6683.png)

**Comment by nodomain** [comment]
See also: https://forum.sentry.io/t/events-seems-to-be-processed-but-not-showing-on-web/13789/2
I am just preparing a cleanup of my messed up CF template.
