### ISSUE TITLE
can import template

### ISSUE THREAD

**Issue by xjg2010go** [Rungutan/sentry-fargate-cf-stack#55]
Hello, when import cloudformation template file, I got these errors, pleas help me check.

The following resource types are not supported for resource import: 

AWS::SecretsManager::Secret,AWS::SecretsManager::Secret,AWS::SecretsManager::Secret,AWS::EC2::VPCGatewayAttachment,AWS::ElasticLoadBalancingV2::TargetGroup,AWS::ElasticLoadBalancingV2::TargetGroup,AWS::EC2::Route,AWS::EC2::SecurityGroupIngress,AWS::EC2::SecurityGroupIngress,AWS::EC2::SecurityGroupIngress,AWS::EC2::NetworkAclEntry,AWS::EC2::NetworkAclEntry,AWS::EC2::NetworkAclEntry,AWS::EC2::NetworkAclEntry,AWS::EC2::SubnetNetworkAclAssociation,AWS::EC2::SubnetNetworkAclAssociation,AWS::RDS::DBSubnetGroup,AWS::EC2::SubnetNetworkAclAssociation,AWS::ElastiCache::SubnetGroup,AWS::EC2::SubnetNetworkAclAssociation,AWS::EC2::SubnetNetworkAclAssociation,AWS::EC2::SubnetRouteTableAssociation,AWS::EC2::SubnetRouteTableAssociation,AWS::EC2::SubnetRouteTableAssociation,AWS::EC2::SubnetNetworkAclAssociation,AWS::EC2::SecurityGroupIngress,AWS::EC2::SecurityGroupIngress,AWS::EC2::SubnetRouteTableAssociation,AWS::EC2::SubnetRouteTableAssociation,AWS::EC2::VPCEndpoint,AWS::EC2::SubnetRouteTableAssociation,AWS::OpsWorks::Stack,Custom::KafkaCreateConfiguration,AWS::ElastiCache::ReplicationGroup,AWS::EC2::Route,AWS::EC2::Route,AWS::EC2::Route,AWS::Route53::RecordSetGroup,AWS::Route53::RecordSetGroup,AWS::Route53::RecordSetGroup,AWS::ElasticLoadBalancingV2::TargetGroup,AWS::ElasticLoadBalancingV2::TargetGroup,AWS::Route53::RecordSetGroup,AWS::ElasticLoadBalancingV2::TargetGroup,AWS::OpsWorks::Layer,AWS::MSK::Cluster,AWS::ApplicationAutoScaling::ScalableTarget,AWS::OpsWorks::Instance,AWS::ApplicationAutoScaling::ScalableTarget,Custom::KafkaGetBrokers,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::OpsWorks::ElasticLoadBalancerAttachment,AWS::ApplicationAutoScaling::ScalingPolicy,Custom::ClickHouseBootstrapSingleExecution,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,AWS::ApplicationAutoScaling::ScalableTarget,Custom::DelayClickHouseBootstrap,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,AWS::ApplicationAutoScaling::ScalingPolicy,Custom::SentryMigrationSingleExecution,Custom::DelaySentryMigration,Custom::SnubaBootstrapSingleExecution,Custom::DelaySnubaBootstrap,Custom::SnubaMigrationsSingleExecution,Custom::DelaySnubaMigrations,Custom::SentryInitialUserSingleExecution

**Comment by mariusmitrofan** [comment]
Stack cannot be imported. Only created
